### ISSUE TITLE
Investigate Firejail for sandboxing.

### ISSUE THREAD

**Issue by iflowfor8hours** [iflowfor8hours/sandcastle#34]
Firejail look promising, but I haven't had a chance to look at how it handles filesystems and other resources. 

https://lwn.net/Articles/671534/
https://l3net.wordpress.com/projects/firejail/

**Comment by jacksingleton** [comment]
https://github.com/avoidr/firejail/blob/tor_support/etc/tor.profile
https://l3net.wordpress.com/2014/06/08/securing-a-web-server-using-a-linux-namespaces-sandbox/

(tor and nginx are bound to public ports and will be the most important to sandbox)
