### ISSUE TITLE
add fail2ban

### ISSUE THREAD

**Issue by jacksingleton** [iflowfor8hours/sandcastle#6]
http://www.fail2ban.org/wiki/index.php/Main_Page

**Comment by iflowfor8hours** [comment]
I started work on this on a branch and got a little stuck on figuring out ways to hammer test the config to make sure it works since I'm not that familiar with fail2ban. apache benchmark seems like a good place to start.

**Comment by conorsch** [comment]
The defaults for fail2ban are better than nothing. You're already using some of @geerlingguy's work, so check out https://github.com/geerlingguy/ansible-role-security. (That role is also convenient for bootstrapping sudoers via a list of usernames.)

Testing fail2ban is another topic altogether. Early on in development I recommend doing it manually: try repeatedly SSHing in with a wrong key and make sure you get banned. Automated testing of fail2ban would be tricky, but you can script the actions in a CI environment and assert failure within a target threshold.

**Comment by iflowfor8hours** [comment]
Added #23 as a starting point, thanks for the heads up on just testing by hand, I was over-complicating things from the start.
